version: '2.1'
services:
#   product:
#     build: .
#     depends_on:
#       postgres:
#         condition: service_healthy
#       redis:
#         condition: service_started

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5